### ISSUE TITLE
Unable to create an app using the CLI

### ISSUE THREAD

**Issue by meisterfranz** [flyandi/mazda-custom-application-sdk#15]
I am trying to create an app with `casdk create abc` but getting this error.
Node version is **18.16.1**
```
node:internal/validators:421
    throw new ERR_INVALID_ARG_TYPE(name, 'Function', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "cb" argument must be of type function. Received undefined
    at maybeCallback (node:fs:187:3)
    at Object.writeFile (node:fs:2191:14)
    at /usr/local/lib/node_modules/casdk/casdk.js:92:6
    at Array.forEach (<anonymous>)
    at createCustomApplication (/usr/local/lib/node_modules/casdk/casdk.js:75:41)
    at Command.<anonymous> (/usr/local/lib/node_modules/casdk/casdk.js:119:4)
    at Command.listener (/usr/local/lib/node_modules/casdk/node_modules/commander/index.js:315:8)
    at Command.emit (node:events:513:28)
    at Command.parseArgs (/usr/local/lib/node_modules/casdk/node_modules/commander/index.js:651:12)
    at Command.parse (/usr/local/lib/node_modules/casdk/node_modules/commander/index.js:474:21) {
  code: 'ERR_INVALID_ARG_TYPE'
}

```

**Comment by thegala** [comment]
You can fix error with changing line 92 in casdk.js with
` fs.writeFileSync(outputLocation + '/' + key, appContent); `
